"""alter commisions column to support Big integers

Revision ID: 113eb73ebba8
Revises:
Create Date: 2025-02-25 01:32:44.959377

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "113eb73ebba8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "deal",
        "total_commissions",
        existing_type=sa.Float(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "deal",
        "total_interests",
        existing_type=sa.Float(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "deal",
        "total_commissions",
        existing_type=sa.BigInteger(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "deal",
        "total_interests",
        existing_type=sa.BigInteger(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
