"""

Revision ID: 136bebfa4686
Revises: 7244d85b3cab
Create Date: 2025-04-18 20:25:32.359999

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "136bebfa4686"
down_revision: Union[str, None] = "7244d85b3cab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("autotrade", "balance_to_use", if_exists=True)
    op.create_index(
        op.f("ix_bot_deal_id"), "bot", ["deal_id"], unique=False, if_not_exists=True
    )
    op.alter_column(
        "deal",
        "total_interests",
        existing_type=sa.BIGINT(),
        type_=sa.Float(),
        nullable=True,
    )
    op.alter_column(
        "deal",
        "total_commissions",
        existing_type=sa.BIGINT(),
        type_=sa.Float(),
        nullable=True,
    )
    op.create_index(
        op.f("ix_exchange_order_bot_id"),
        "exchange_order",
        ["bot_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_exchange_order_paper_trading_id"),
        "exchange_order",
        ["paper_trading_id"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_constraint(
        "exchange_order_paper_trading_id_fkey", "exchange_order", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "exchange_order",
        "paper_trading",
        ["paper_trading_id"],
        ["id"],
        ondelete="CASCADE",
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_paper_trading_deal_id"), "paper_trading", ["deal_id"], unique=False, if_not_exists=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_paper_trading_deal_id"), table_name="paper_trading")
    op.create_foreign_key(
        "exchange_order_paper_trading_id_fkey",
        "exchange_order",
        "paper_trading",
        ["paper_trading_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_exchange_order_paper_trading_id"), table_name="exchange_order"
    )
    op.drop_index(op.f("ix_exchange_order_bot_id"), table_name="exchange_order")
    op.alter_column(
        "deal",
        "total_commissions",
        existing_type=sa.Float(),
        type_=sa.BIGINT(),
        nullable=False,
    )
    op.alter_column(
        "deal",
        "total_interests",
        existing_type=sa.Float(),
        type_=sa.BIGINT(),
        nullable=False,
    )
    op.drop_index(op.f("ix_bot_deal_id"), table_name="bot")
    op.add_column(
        "autotrade",
        sa.Column("balance_to_use", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
