"""Rename quote assets correctly

Revision ID: 1d00dd25c31f
Revises: 4bc0f1cb12e2
Create Date: 2025-08-27 00:42:04.351273

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1d00dd25c31f"
down_revision: Union[str, None] = "4bc0f1cb12e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add quote_asset as nullable with default
    op.add_column(
        "bot",
        sa.Column(
            "quote_asset",
            sa.Enum("USDC", "BTC", "BNB", name="quoteassets"),
            nullable=True,
            server_default="USDC",
        ),
    )
    # 3. Set NOT NULL and remove default
    op.alter_column(
        "bot",
        "quote_asset",
        existing_type=sa.Enum("USDC", "BTC", "BNB", name="quoteassets"),
        nullable=False,
        server_default=None,
    )
    # 4. Drop base_asset column
    op.drop_column("bot", "base_asset")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bot",
        sa.Column(
            "base_asset",
            postgresql.ENUM("USDC", "BTC", "BNB", name="baseassets"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("bot", "quote_asset")
    # ### end Alembic commands ###
