"""create asset_index table

Revision ID: 231078b0422d
Revises: 680413ed7dd3
Create Date: 2025-08-18 22:58:40.435504

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "231078b0422d"
down_revision: Union[str, None] = "2a7c1f0c1a3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_index",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("name", sa.String(), nullable=False, default=""),
        sa.Column("value", sa.String(), nullable=False, default=""),
    )
    op.add_column(
        "symbol",
        sa.Column("description", sa.String(), nullable=False, server_default=""),
    )
    op.create_table(
        "symbolindexlink",
        sa.Column(
            "symbol_id", sa.String(), sa.ForeignKey("symbol.id"), primary_key=True
        ),
        sa.Column(
            "asset_index_id",
            sa.String(),
            sa.ForeignKey("asset_index.id"),
            primary_key=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("symbolindexlink")
    op.drop_column("symbol", "description")
    op.drop_table("asset_index")
    # ### end Alembic commands ###
