"""create asset_index table

Revision ID: 28b250221d55
Revises: 2a7c1f0c1a3b
Create Date: 2025-08-18 23:38:24.590544

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "28b250221d55"
down_revision: Union[str, None] = "2a7c1f0c1a3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create asset_index table only if it does not exist
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'asset_index') THEN
                CREATE TABLE asset_index (
                    id VARCHAR PRIMARY KEY,
                    name VARCHAR NOT NULL DEFAULT ''
                );
            END IF;
        END$$;
        """
    )
    # Add description column to symbol only if it does not exist
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name='symbol' AND column_name='description'
            ) THEN
                ALTER TABLE symbol ADD COLUMN description VARCHAR NOT NULL DEFAULT '';
            END IF;
        END$$;
        """
    )
    # Create symbolindexlink table only if it does not exist
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'symbolindexlink') THEN
                CREATE TABLE symbolindexlink (
                    symbol_id VARCHAR REFERENCES symbol(id),
                    asset_index_id VARCHAR REFERENCES asset_index(id),
                    PRIMARY KEY (symbol_id, asset_index_id)
                );
            END IF;
        END$$;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("symbolindexlink")
    op.drop_column("symbol", "description", if_exists=True)
    op.drop_table("asset_index")
    # ### end Alembic commands ###
