"""Add margin_short_reversal to autotrade settings

Revision ID: 46c739c73ec3
Revises: f5681454997c
Create Date: 2025-05-30 04:42:58.778754

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "46c739c73ec3"
down_revision: Union[str, None] = "f5681454997c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add 'autoswitch' column to 'autotrade' if it does not exist
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns("autotrade")]
    if "autoswitch" not in columns:
        op.add_column(
            "autotrade",
            sa.Column(
                "autoswitch",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            ),
        )
    columns_test = [col["name"] for col in inspector.get_columns("test_autotrade")]
    if "autoswitch" not in columns_test:
        op.add_column(
            "test_autotrade",
            sa.Column(
                "autoswitch",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            ),
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_autotrade", "autoswitch", if_exists=True)
    op.drop_column("autotrade", "autoswitch", if_exists=True)
    # ### end Alembic commands ###
