"""Move base_order_size field to deal table

Revision ID: 49859b6aac65
Revises: f319e9aea047
Create Date: 2025-09-02 22:42:40.666943

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "49859b6aac65"
down_revision: Union[str, None] = "f319e9aea047"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add the new column to deal
    op.add_column("deal", sa.Column("base_order_size", sa.Float(), nullable=True))

    # 2. Copy values from bot.base_order_size to deal.base_order_size using deal_id in bot
    op.execute("""
        UPDATE deal
        SET base_order_size = (
            SELECT bot.base_order_size FROM bot WHERE bot.deal_id = deal.id
        )
        WHERE EXISTS (SELECT 1 FROM bot WHERE bot.deal_id = deal.id)
    """)

    # 3. Drop the column from bot
    op.drop_column("bot", "base_order_size")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deal", "base_order_size")
    op.add_column(
        "bot",
        sa.Column(
            "base_order_size",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
