"""add paper_trading_table missing fields from bot table

Revision ID: 4a1726cbd311
Revises: f79b8d93c715
Create Date: 2025-09-04 23:23:24.104329

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a1726cbd311"
down_revision: Union[str, None] = "f79b8d93c715"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add quote_asset as nullable first
    op.add_column(
        "paper_trading",
        sa.Column(
            "quote_asset",
            sa.Enum("USDC", "BTC", "ETH", name="quoteassets"),
            nullable=True,
        ),
    )
    # Set default value for existing rows
    op.execute(
        "UPDATE paper_trading SET quote_asset = 'USDC' WHERE quote_asset IS NULL;"
    )
    # Alter column to NOT NULL
    op.alter_column("paper_trading", "quote_asset", nullable=False)

    # Add fiat_order_size as nullable first
    op.add_column(
        "paper_trading", sa.Column("fiat_order_size", sa.Float(), nullable=True)
    )
    # Set default value for existing rows
    op.execute(
        "UPDATE paper_trading SET fiat_order_size = 0.0 WHERE fiat_order_size IS NULL;"
    )
    # Alter column to NOT NULL
    op.alter_column("paper_trading", "fiat_order_size", nullable=False)

    op.drop_column("paper_trading", "base_order_size")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "paper_trading",
        sa.Column(
            "base_order_size",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("paper_trading", "fiat_order_size")
    op.drop_column("paper_trading", "quote_asset")
    # ### end Alembic commands ###
