"""

Revision ID: 9ef3d98bd4d9
Revises: 136bebfa4686
Create Date: 2025-04-21 03:32:47.636809

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ef3d98bd4d9"
down_revision: Union[str, None] = "136bebfa4686"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "autotrade", ["id"])
    op.drop_index("ix_exchange_order_paper_trading_id", table_name="exchange_order")
    op.drop_constraint(
        "exchange_order_paper_trading_id_fkey", "exchange_order", type_="foreignkey"
    )
    op.drop_column("exchange_order", "paper_trading_id", if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exchange_order",
        sa.Column("paper_trading_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "exchange_order_paper_trading_id_fkey",
        "exchange_order",
        "paper_trading",
        ["paper_trading_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        "ix_exchange_order_paper_trading_id",
        "exchange_order",
        ["paper_trading_id"],
        unique=False,
        if_not_exists=True,
    )
    # ### end Alembic commands ###
