"""update order timestamp to big int

Revision ID: b2503d66f907
Revises: 4a1726cbd311
Create Date: 2025-09-06 16:19:19.683185

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2503d66f907"
down_revision: Union[str, None] = "4a1726cbd311"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Change 'timestamp' and 'order_id' columns in 'exchange_order' table to BIGINT
    op.alter_column("exchange_order", "timestamp", type_=sa.BigInteger())
    op.alter_column("exchange_order", "order_id", type_=sa.BigInteger())


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert 'timestamp' and 'order_id' columns in 'exchange_order' table to INTEGER
    op.alter_column("exchange_order", "timestamp", type_=sa.Integer())
    op.alter_column("exchange_order", "order_id", type_=sa.Integer())


# ### end Alembic commands ###
