"""Add new fiat_order_size field

Revision ID: f319e9aea047
Revises: 1d00dd25c31f
Create Date: 2025-09-02 22:11:15.136430

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f319e9aea047"
down_revision: Union[str, None] = "1d00dd25c31f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add the new column as nullable (to allow data migration)
    op.add_column("bot", sa.Column("fiat_order_size", sa.Float(), nullable=True))

    # 2. Fill new column with values from base_order_size
    op.execute("""
        UPDATE bot SET fiat_order_size = base_order_size
    """)

    # 3. Alter the column to set NOT NULL and default value
    op.alter_column(
        "bot",
        "fiat_order_size",
        existing_type=sa.Float(),
        nullable=False,
        server_default=sa.text("0"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bot", "fiat_order_size")
    # ### end Alembic commands ###
