"""Add new enum market type

Revision ID: f5152a7a008b
Revises: 7775eb0b8c12
Create Date: 2026-02-01 17:40:14.368714

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f5152a7a008b"
down_revision: Union[str, Sequence[str], None] = "7775eb0b8c12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bot",
        sa.Column(
            "market_type",
            sa.Enum("SPOT", "MARGIN", "FUTURES", name="markettype"),
            nullable=True,
        ),
    )
    op.add_column(
        "paper_trading",
        sa.Column(
            "market_type",
            sa.Enum("SPOT", "MARGIN", "FUTURES", name="markettype"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("paper_trading", "market_type")
    op.drop_column("bot", "market_type")
    op.execute("DROP TYPE IF EXISTS markettype")
    # ### end Alembic commands ###
