"""

Revision ID: f5681454997c
Revises: 9ef3d98bd4d9
Create Date: 2025-05-21 21:44:40.710086

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f5681454997c"
down_revision: Union[str, None] = "9ef3d98bd4d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop the enum type if it exists before creating it (handles previous bad state)
    op.execute("DROP TYPE IF EXISTS orderstatus;")
    # Explicitly create the enum type before altering columns
    op.execute(
        """
        CREATE TYPE orderstatus AS ENUM (
            'NEW',
            'PARTIALLY_FILLED',
            'FILLED',
            'CANCELED',
            'REJECTED',
            'EXPIRED'
        )
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "exchange_order",
        "status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "NEW",
            "PARTIALLY_FILLED",
            "FILLED",
            "CANCELED",
            "REJECTED",
            "EXPIRED",
            name="orderstatus",
        ),
        existing_nullable=False,
        postgresql_using="UPPER(status)::orderstatus",
    )
    op.alter_column(
        "fake_order",
        "status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "NEW",
            "PARTIALLY_FILLED",
            "FILLED",
            "CANCELED",
            "REJECTED",
            "EXPIRED",
            name="orderstatus",
        ),
        existing_nullable=False,
        postgresql_using="UPPER(status)::orderstatus",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fake_order",
        "status",
        existing_type=sa.Enum(
            "NEW",
            "PARTIALLY_FILLED",
            "FILLED",
            "CANCELED",
            "REJECTED",
            "EXPIRED",
            name="orderstatus",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "exchange_order",
        "status",
        existing_type=sa.Enum(
            "NEW",
            "PARTIALLY_FILLED",
            "FILLED",
            "CANCELED",
            "REJECTED",
            "EXPIRED",
            name="orderstatus",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.execute("DROP TYPE IF EXISTS orderstatus;")
    # ### end Alembic commands ###
