"""

Revision ID: f5681454997c
Revises: 9ef3d98bd4d9
Create Date: 2025-05-21 21:44:40.710086

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f5681454997c"
down_revision: Union[str, None] = "9ef3d98bd4d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE dealtype ADD VALUE IF NOT EXISTS 'trailling_profit'")
    # SAFE FIX: Do not drop orderstatus type if columns depend on it
    # op.execute("DROP TYPE IF EXISTS orderstatus;")
    # Explicitly create the enum type before altering columns
    # SAFE FIX: Only create type if it does not exist
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'orderstatus') THEN
                CREATE TYPE orderstatus AS ENUM (
                    'NEW',
                    'PARTIALLY_FILLED',
                    'FILLED',
                    'CANCELED',
                    'REJECTED',
                    'EXPIRED'
                );
            END IF;
        END$$;
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "exchange_order",
        "status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "NEW",
            "PARTIALLY_FILLED",
            "FILLED",
            "CANCELED",
            "REJECTED",
            "EXPIRED",
            name="orderstatus",
        ),
        existing_nullable=False,
        postgresql_using="status::orderstatus",
    )
    op.alter_column(
        "fake_order",
        "status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "NEW",
            "PARTIALLY_FILLED",
            "FILLED",
            "CANCELED",
            "REJECTED",
            "EXPIRED",
            name="orderstatus",
        ),
        existing_nullable=False,
        postgresql_using="status::orderstatus",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fake_order",
        "status",
        existing_type=sa.Enum(
            "NEW",
            "PARTIALLY_FILLED",
            "FILLED",
            "CANCELED",
            "REJECTED",
            "EXPIRED",
            name="orderstatus",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "exchange_order",
        "status",
        existing_type=sa.Enum(
            "NEW",
            "PARTIALLY_FILLED",
            "FILLED",
            "CANCELED",
            "REJECTED",
            "EXPIRED",
            name="orderstatus",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # SAFE FIX: Do not drop orderstatus type if columns depend on it
    # op.execute("DROP TYPE IF EXISTS orderstatus;")
    # ### end Alembic commands ###
