version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "yearly"
    commit-message:
      # Prefix all commit messages with "npm"
      prefix: "npm"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "yearly"
    # Include a list of updated dependencies
    # with a prefix determined by the dependency group
    commit-message:
      prefix: "pip prod"
      prefix-development: "pip dev"
      include: "scope"