networks:
  kafka_network:
    driver: bridge

services:
  api_db:
    image: postgres
    container_name: binbot_api_db
    restart: on-failure
    networks:
      - kafka_network
    volumes:
      - pg_data:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 30s

  # api:
  #   build:
  #     context: .
  #     dockerfile: api/Dockerfile
  #   networks:
  #     - kafka_network
  #   restart: no
  #   container_name: binbot
  #   depends_on:
  #     api_db:
  #       condition: service_healthy
  #       restart: true
  #   env_file:
  #     - .env
  #   environment:
  #     - POSTGRES_HOSTNAME=api_db
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://api:8000/ || exit 1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 20s

  # api_nginx:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: binbot_nginx
  #   restart: unless-stopped
  #   networks:
  #     - kafka_network
  #   ports:
  #     - 8008:8000
  #     - 8007:80
  #   depends_on:
  #     - api
  #   env_file:
  #     - .env
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:8008 || exit 1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 20s

  # streaming:
  #   build:
  #     context: .
  #     dockerfile: streaming/Dockerfile
  #   image: binbot_streaming
  #   env_file:
  #     - .env
  #   restart: on-failure
  #   container_name: binbot_streaming
  #   depends_on:
  #     - api

  # cronjobs:
  #   build:
  #     context: .
  #     dockerfile: cronjobs/Dockerfile
  #   image: binbot_cronjobs
  #   env_file:
  #     - .env
  #   restart: on-failure
  #   container_name: binbot_cronjobs
  #   depends_on:
  #     - api

volumes:
  pg_data:
