FROM python:3.10
RUN apt-get update && apt-get install -y --no-install-recommends build-essential python3-dev
COPY api api
WORKDIR api
RUN pip3 install pipenv
RUN pipenv install --system --deploy --ignore-pipfile --clear
ENTRYPOINT ["python3", "-u", "cronjobs.py"]

STOPSIGNAL SIGTERM
