version: "3.8"
services:
  db:
    image: mongo:latest
    container_name: binbot_db
    restart: on-failure
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_AUTH_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_AUTH_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_APP_DATABASE}
    ports:
      - 27018:27017
    volumes:
      - ./mongo_data:/data/db

  # api:
  #   build: .
  #   image: binbot_api
  #   restart: on-failure
  #   container_name: binbot
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  #   ports:
  #     - 8007:80
  #     - 8008:8006

  # streaming:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.streaming
  #   image: binbot_streaming
  #   env_file:
  #     - .env
  #   restart: on-failure
  #   container_name: binbot_streaming
  #   depends_on:
  #     - api
  #     - db

volumes:
  mongo_data:
