version: '3.7'
services:
  db:
    image: mongo:latest
    container_name: binbot_db
    restart: on-failure
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_AUTH_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_AUTH_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_APP_DATABASE}
    ports:
      - 27018:27017
    volumes:
      - ./mongo_data:/data/db
  
  api:
    image: binbot:staging
    restart: on-failure
    container_name: binbot
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8007:80
      - 8008:8006

volumes:
  mongo_data:
