.PHONY: up down test test-streaming test-cronjobs \
        build build-api build-streaming build-cronjobs \
        migrate migrate-reset create-migration \
        format delete-revision upgrade-pybinbot export-bot-records

ifneq (,$(wildcard .env))
    include .env
    export
endif

VENV=./.venv
EXPORT_BOT_SCRIPT=/Users/carkod/.codex/skills/binbot-db-export-records/scripts/export_bot_records.py

cmd-exists-%:
	@hash $(*) > /dev/null 2>&1 || \
		(echo "ERROR: '$(*)' must be installed and available on your PATH."; exit 1)

# ── Docker ────────────────────────────────────────────────────────────────────

up:  ## Run Docker Compose services
	docker compose -f compose.yml up --pull always -d --build

down:  ## Shutdown Docker Compose services
	docker compose -f compose.yml down --volumes --remove-orphans

build-api:  ## Build the API Docker image
	docker build -t carloswufei/binbot:local -f api/Dockerfile .

build-streaming:  ## Build the streaming Docker image
	docker build -t carloswufei/binbot_streaming:local -f streaming/Dockerfile .

build-cronjobs:  ## Build the cronjobs Docker image
	docker build -t carloswufei/binbot_cronjobs:local -f cronjobs/Dockerfile .

build: build-api build-streaming build-cronjobs  ## Build all service images

# ── Tests ─────────────────────────────────────────────────────────────────────

test:  ## Run api test suite
	uv run pytest api/tests/ -v

test-streaming:  ## Smoke-test streaming entry point (import check)
	uv run python -c "import streaming.main; print('streaming.main OK')"

test-cronjobs:  ## Smoke-test cronjobs entry point (import check)
	uv run python -c "import cronjobs.main; print('cronjobs.main OK')"

dump-fixtures:  ## Dump test fixtures from database (requires DB to be running)
	uv run python api/tests/fixtures/dump_fixtures.py

# ── Formatting & linting ──────────────────────────────────────────────────────

format:  ## Format, lint, and type-check all service folders
	@uv run ruff format .
	@uv run ruff check . --fix
	@uv run mypy .

# ── Migrations ────────────────────────────────────────────────────────────────

migrate:  ## Apply latest alembic migrations
	uv run alembic upgrade head
	uv run alembic stamp head
	@if [ -n "$(m)" ]; then \
		uv run alembic revision --autogenerate -m "$(m)" --head head; \
	fi

migrate-reset:  ## Downgrade one revision then upgrade
	uv run alembic downgrade -1
	uv run alembic upgrade head

create-migration:  ## Create a new autogenerated migration (m=<message>)
	@if [ -z "$(m)" ]; then \
		echo "ERROR: You must provide a migration message. Usage: make create-migration m='migration message'"; \
		exit 1; \
	fi
	uv run alembic revision --autogenerate -m "$(m)"

# ── Utilities ─────────────────────────────────────────────────────────────────

upgrade-pybinbot:
	source .venv/bin/activate;
	@uv cache clean
	@uv remove pybinbot
	@uv add pybinbot --upgrade
	@uv sync --extra dev

delete-revision:  ## Delete a specific Alembic revision from the database (revision=<rev>)
	@if [ -z "$(revision)" ]; then \
		echo "ERROR: You must provide a revision. Usage: make delete-revision revision=<revision>"; \
		exit 1; \
	fi
	@echo "POSTGRES_PASSWORD: $(POSTGRES_PASSWORD)"
	@echo "Deleting revision $(revision) from alembic_version table..."
	docker exec -ti binbot_api_db sh -c "PGPASSWORD=$(POSTGRES_PASSWORD) psql -U $(POSTGRES_USER) -d $(POSTGRES_DB) -c \"DELETE FROM alembic_version WHERE version_num = '$(revision)';\""

export-bot-records:  ## Export bots using Codex script (BOT_ID=<uuid>)
	@if [ -z "$(BOT_ID)" ]; then \
		echo "ERROR: You must provide BOT_ID. Usage: make export-bot-records BOT_ID=<uuid>"; \
		exit 1; \
	fi
	@python3 $(EXPORT_BOT_SCRIPT) "$(BOT_ID)"
