#!/bin/bash
gunicorn -b 0.0.0.0:8006 --access-logfile "/var/log/nginx/web-access.log" --error-logfile "/var/log/nginx/web-error.log" --timeout 120 --log-level debug -e GEVENT_RESOLVER=ares -D api.main:app
nginx -g 'daemon off;'
