#!/bin/bash
gunicorn -w 3 -b :8006 -t 90 --access-logfile "/var/log/nginx/web-access.log" --error-logfile "/var/log/nginx/web-error.log" --preload --timeout 120 --capture-output --log-level debug -D api.main:app
# ln -sf /dev/stdout /var/log/nginx/web-access.log && ln -sf /dev/stderr /var/log/nginx/web-error.log
nginx -g 'daemon off;'
