#!/bin/bash
gunicorn -w 3 -b 127.0.0.1:8006 -t 90 --access-logfile "/var/log/nginx/web-access.log" --error-logfile "/var/log/nginx/web-error.log" --preload --timeout 120 --capture-output --log-level debug -D api.main:app
nginx -g 'daemon off;'
