GET http://localhost:5000/bot/ HTTP/1.1

###

GET http://localhost:5000/bot/5de3d4571f30fed6914d2118 HTTP/1.1

###

POST http://localhost:5000/bot/ HTTP/1.1
content-Type: application/json

{
    "pair": "BNBUSDT",
    "active": "false",
    "strategy": "long",
    "name": "Default Bot",
    "so_size": "0.0001",
    "take_profit": "0.003",
    "price_deviation_so": "0.0063"
}

###
PUT http://localhost:5000/bot/ HTTP/1.1
content-Type: application/json

{
    "_id": "5de3d4571f30fed6914d2118",
    "pair": "BTCUSDT",
    "strategy": "short",
    "name": "Pepe",
    "maxSOCount": "2",
    "balanceUsage": "1",
    "baseOrderSize": "0.0001"
}

###
DELETE http://localhost:5000/bot/5dc8d91b34ee965b19a4fd4e HTTP/1.1

###

GET http://localhost:5000/bot/activate/5f7fa3d0b01710bad6564eda HTTP/1.1
