GET http://localhost:5000/bot/ HTTP/1.1

###

GET http://localhost:5000/bot/5f82420dad1307fd880ca7f2 HTTP/1.1

###

POST http://localhost:5000/bot/ HTTP/1.1
content-Type: application/json

{
    "pair": "BUSDSTORJ",
    "active": "false",
    "strategy": "long",
    "name": "Initial BUSD",
    "so_size": "0",
    "take_profit": "0.003",
    "price_deviation_so": "0"
}

###
PUT http://localhost:5000/bot/5f82420dad1307fd880ca7f2 HTTP/1.1
content-Type: application/json

{
    "pair": "STORJBUSD",
    "name": "Initial BUSD"
}

###
DELETE http://localhost:5000/bot/5dc8d91b34ee965b19a4fd4e HTTP/1.1

###

GET http://localhost:5000/bot/activate/5f82420dad1307fd880ca7f2 HTTP/1.1
