GET http://localhost:5000/bot/ HTTP/1.1

###

GET http://localhost:5000/bot/5de3d4571f30fed6914d2118 HTTP/1.1

###

POST http://localhost:5000/bot/ HTTP/1.1

{
    "pair": "BTCUSDT",
    "active": "true",
    "strategy": "short",
    "name": "BTC hedging bot",
    "maxSOCount": "3",
    "balanceUsage": "1",
    "baseOrderSize": "0.0001",
    "baseOrderType": "limit",
    "startCondition": "true",
    "soSize": "0.0001",
    "takeProfit": "0.003",
    "priceDeviationSO": "0.0063",
    "trailling": "false",
    "traillingDeviation": "0.0063",
    "dealMinValue": "0",
    "cooldown": "0"
}

###
PUT http://localhost:5000/bot/ HTTP/1.1

{
    "_id": "5de3d4571f30fed6914d2118",
    "pair": "BTCUSDT",
    "active": "true",
    "strategy": "long",
    "name": "BTC USDT long bot",
    "maxSOCount": "2",
    "balanceUsage": "1",
    "baseOrderSize": "0.0001",
    "baseOrderType": "limit",
    "startCondition": "true",
    "soSize": "0.0001",
    "takeProfit": "0.003",
    "priceDeviationSO": "0.0063",
    "trailling": "false",
    "traillingDeviation": "0.0063",
    "dealMinValue": "0",
    "cooldown": "0"
}

###
DELETE http://localhost:5000/bot/5dc8d91b34ee965b19a4fd4e HTTP/1.1

###

GET http://localhost:5000/bot/activate/5de3d4571f30fed6914d2118 HTTP/1.1
