### Store in the db
GET http://localhost:5000/research/save-correlation/1d/20 HTTP/1.1

###
GET http://localhost:5000/research/correlation?market=BTCUSDT HTTP/1.1

### Get Bolliguer buy/sell signals
GET http://localhost:5000/research/signals HTTP/1.1

### Signals with filters and orderby
GET http://localhost:5000/research/signals?filterby=side&filter=BUY&orderby=spread&order=-1 HTTP/1.1

###
GET http://localhost:5000/research/signals?order_by=price_change_24&order=true HTTP/1.1

### Get historical signals with filters and orderby
GET http://localhost:5000/research/historical-signals HTTP/1.1




### Add blacklist
POST http://localhost:5000/research/blacklist HTTP/1.1
content-Type: application/json

{ "pair": "ETHBTC", "reason": "Controlled graph" }

### Get all blacklist coins
GET http://localhost:5000/research/blacklist HTTP/1.1




### Get research settings
GET http://localhost:5000/research/controller HTTP/1.1 
content-Type: application/json

### Edit settings. Delete show not be allowed
PUT http://localhost:5000/research/controller HTTP/1.1
content-Type: application/json

{
    "candlestick_interval": "1d",
    "autotrade": 0,
    "errors": []
}


### Get bot autotrade settings
GET http://localhost:5000/research/test-autotrade-settings HTTP/1.1 
content-Type: application/json

### Get bot autotrade settings
PUT http://localhost:5000/research/test-autotrade-settings HTTP/1.1 
content-Type: application/json

{
    "_id": "test_autotrade_settings",
    "balance_size_to_use":100,
    "balance_to_use": "GBP",
    "candlestick_interval": "15m",
    "stop_loss": 3,
    "take_profit": 2.4,
    "telegram_signals": 1,
    "test_autotrade": 0,
    "trailling": "false",
    "trailling_deviation": 3,
    "trailling_profit": 2.4
}

### Get 3 commas preset ots
GET http://localhost:5000/research/3commas-presets HTTP/1.1 
content-Type: application/json

### Get 3 commas preset signals
GET http://localhost:5000/research/3commas-items HTTP/1.1 
content-Type: application/json
