### Store in the db
GET http://localhost:5000/research/save-correlation/1d/20 HTTP/1.1

###
GET http://localhost:5000/research/correlation?market=BTCUSDT HTTP/1.1

### Get Bolliguer buy/sell signals
GET http://localhost:5000/research/signals HTTP/1.1

### Signals with filters and orderby
GET http://localhost:5000/research/signals?filterby=side&filter=BUY&orderby=spread&order=-1 HTTP/1.1

###
GET http://localhost:5000/research/signals?order_by=price_change_24&order=true HTTP/1.1

### Get historical signals with filters and orderby
GET http://localhost:5000/research/historical-signals HTTP/1.1

### Add blacklist
POST http://localhost:5000/research/blacklisted HTTP/1.1
content-Type: application/json

{ "symbol": "TRXBTC", "reason": "Controlled graph" }

### Get all blacklist coins
GET http://localhost:5000/research/blacklisted HTTP/1.1

### Get research settings
GET http://localhost:5000/research/controller HTTP/1.1 
content-Type: application/json

### Add blacklist
PUT http://localhost:5000/research/controller HTTP/1.1
content-Type: application/json

{ "candlestick_interval": "1hr", "autotrade": 0 }

