#!/usr/bin/env python3
"""
Script to dump test fixtures from the actual database.

This script connects to your PostgreSQL database, fetches the current data,
and generates the symbol_fixtures.py file with Python code that can be used
to seed the test database.

Usage:
    python tests/fixtures/dump_fixtures.py
    # Or via make:
    make dump-fixtures

Requirements:
    - Database must be running
    - Environment variables must be set (POSTGRES_USER, POSTGRES_PASSWORD, etc.)
"""

import sys
from pathlib import Path

# Add parent directory to path to import from project
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from sqlmodel import Session, select
from api.databases.utils import engine
from api.databases.tables.symbol_table import SymbolTable
from api.databases.tables.symbol_exchange_table import SymbolExchangeTable


def dump_symbols(session: Session, limit: int = 10):
    """Dump symbol data from database"""
    statement = select(SymbolTable).limit(limit)
    symbols = session.exec(statement).unique().all()

    output = []
    output.append("def get_test_symbols():")
    output.append(
        '    """Returns list of test symbol records with their exchange values"""'
    )
    output.append("    return [")

    for symbol in symbols:
        # Get exchange values for this symbol
        exchange_values = (
            session.exec(
                select(SymbolExchangeTable).where(
                    SymbolExchangeTable.symbol_id == symbol.id
                )
            )
            .unique()
            .all()
        )

        output.append("        {")
        output.append('            "symbol": SymbolTable(')
        output.append(f'                id="{symbol.id}",')
        output.append(f"                active={symbol.active},")
        output.append(f'                blacklist_reason="{symbol.blacklist_reason}",')
        output.append(f'                quote_asset="{symbol.quote_asset}",')
        output.append(f'                base_asset="{symbol.base_asset}",')
        output.append(f"                cooldown={symbol.cooldown},")
        output.append(f"                cooldown_start_ts={symbol.cooldown_start_ts},")
        output.append(f'                description="{symbol.description}",')
        output.append(f"                created_at={symbol.created_at},")
        output.append(f"                updated_at={symbol.updated_at},")
        output.append("            ),")
        output.append('            "exchange_values": [')

        for ev in exchange_values:
            output.append("                SymbolExchangeTable(")
            output.append(
                f"                    exchange_id=ExchangeId.{ev.exchange_id.value.upper()},"
            )
            output.append(f'                    symbol_id="{ev.symbol_id}",')
            output.append(f"                    min_notional={ev.min_notional},")
            output.append(
                f"                    is_margin_trading_allowed={ev.is_margin_trading_allowed},"
            )
            output.append(f"                    price_precision={ev.price_precision},")
            output.append(f"                    qty_precision={ev.qty_precision},")
            output.append("                ),")

        output.append("            ],")
        output.append("        },")

    output.append("    ]")
    output.append("\n")
    return "\n".join(output)


def generate_fixture_file(
    symbols_limit: int = 10,
):
    """Generate the complete fixture file"""

    header = '''"""
Test fixtures for symbol data.
This file was auto-generated by dump_fixtures.py
To regenerate: make dump-fixtures
"""

from api.databases.tables.symbol_table import SymbolTable
from api.databases.tables.symbol_exchange_table import SymbolExchangeTable
from pybinbot import ExchangeId


'''

    with Session(engine) as session:
        symbols_code = dump_symbols(session, symbols_limit)

    output = header + symbols_code

    # Write to file
    fixture_file = Path(__file__).parent / "symbol_fixtures.py"
    fixture_file.write_text(output)

    print(f"✅ Fixtures dumped to {fixture_file}")
    print(f"   - Symbols: {symbols_limit} (with exchange values)")


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Dump test fixtures from database")
    parser.add_argument(
        "--symbols", type=int, default=10, help="Number of symbols to dump"
    )

    args = parser.parse_args()

    try:
        generate_fixture_file(args.symbols)
    except Exception as e:
        print(f"❌ Error dumping fixtures: {e}")
        sys.exit(1)
