"""
Test fixtures for symbol data.
This file was auto-generated by dump_fixtures.py
To regenerate: make dump-fixtures
"""

from databases.tables.symbol_table import SymbolTable
from databases.tables.symbol_exchange_table import SymbolExchangeTable
from pybinbot import ExchangeId


def get_test_symbols():
    """Returns list of test symbol records with their exchange values"""
    return [
        {
            "symbol": SymbolTable(
                id="GASBTC",
                active=True,
                blacklist_reason="",
                quote_asset="",
                base_asset="",
                cooldown=0,
                cooldown_start_ts=0,
                description="",
                created_at=1763521181531,
                updated_at=1763521172856,
            ),
            "exchange_values": [
                SymbolExchangeTable(
                    exchange_id=ExchangeId.BINANCE,
                    symbol_id="GASBTC",
                    min_notional=0.0001,
                    is_margin_trading_allowed=False,
                    price_precision=7,
                    qty_precision=1,
                ),
                SymbolExchangeTable(
                    exchange_id=ExchangeId.KUCOIN,
                    symbol_id="GASBTC",
                    min_notional=0.01,
                    is_margin_trading_allowed=False,
                    price_precision=7,
                    qty_precision=3,
                ),
            ],
        },
        {
            "symbol": SymbolTable(
                id="LRCBTC",
                active=True,
                blacklist_reason="",
                quote_asset="",
                base_asset="",
                cooldown=0,
                cooldown_start_ts=0,
                description="",
                created_at=1763521181640,
                updated_at=1763521172856,
            ),
            "exchange_values": [
                SymbolExchangeTable(
                    exchange_id=ExchangeId.BINANCE,
                    symbol_id="LRCBTC",
                    min_notional=0.0001,
                    is_margin_trading_allowed=False,
                    price_precision=8,
                    qty_precision=0,
                ),
            ],
        },
        {
            "symbol": SymbolTable(
                id="LRCETH",
                active=True,
                blacklist_reason="",
                quote_asset="",
                base_asset="",
                cooldown=0,
                cooldown_start_ts=0,
                description="",
                created_at=1763521181698,
                updated_at=1763521172856,
            ),
            "exchange_values": [
                SymbolExchangeTable(
                    exchange_id=ExchangeId.BINANCE,
                    symbol_id="LRCETH",
                    min_notional=0.001,
                    is_margin_trading_allowed=False,
                    price_precision=8,
                    qty_precision=0,
                ),
            ],
        },
        {
            "symbol": SymbolTable(
                id="BNBETH",
                active=True,
                blacklist_reason="",
                quote_asset="",
                base_asset="",
                cooldown=0,
                cooldown_start_ts=0,
                description="",
                created_at=1763521181585,
                updated_at=1763521172856,
            ),
            "exchange_values": [
                SymbolExchangeTable(
                    exchange_id=ExchangeId.BINANCE,
                    symbol_id="BNBETH",
                    min_notional=0.001,
                    is_margin_trading_allowed=False,
                    price_precision=4,
                    qty_precision=3,
                ),
            ],
        },
        {
            "symbol": SymbolTable(
                id="BNBBTC",
                active=True,
                blacklist_reason="",
                quote_asset="",
                base_asset="",
                cooldown=0,
                cooldown_start_ts=0,
                description="",
                created_at=1763521181362,
                updated_at=1763521172856,
            ),
            "exchange_values": [
                SymbolExchangeTable(
                    exchange_id=ExchangeId.BINANCE,
                    symbol_id="BNBBTC",
                    min_notional=0.0001,
                    is_margin_trading_allowed=False,
                    price_precision=6,
                    qty_precision=3,
                ),
                SymbolExchangeTable(
                    exchange_id=ExchangeId.KUCOIN,
                    symbol_id="BNBBTC",
                    min_notional=0.001,
                    is_margin_trading_allowed=False,
                    price_precision=6,
                    qty_precision=3,
                ),
            ],
        },
        {
            "symbol": SymbolTable(
                id="LTCBTC",
                active=True,
                blacklist_reason="",
                quote_asset="",
                base_asset="",
                cooldown=0,
                cooldown_start_ts=0,
                description="",
                created_at=1763521181308,
                updated_at=1763521172856,
            ),
            "exchange_values": [
                SymbolExchangeTable(
                    exchange_id=ExchangeId.BINANCE,
                    symbol_id="LTCBTC",
                    min_notional=0.0001,
                    is_margin_trading_allowed=False,
                    price_precision=6,
                    qty_precision=3,
                ),
                SymbolExchangeTable(
                    exchange_id=ExchangeId.KUCOIN,
                    symbol_id="LTCBTC",
                    min_notional=0.001,
                    is_margin_trading_allowed=True,
                    price_precision=5,
                    qty_precision=2,
                ),
            ],
        },
        {
            "symbol": SymbolTable(
                id="QTUMBTC",
                active=True,
                blacklist_reason="",
                quote_asset="",
                base_asset="",
                cooldown=0,
                cooldown_start_ts=0,
                description="",
                created_at=1763521181749,
                updated_at=1763521172856,
            ),
            "exchange_values": [
                SymbolExchangeTable(
                    exchange_id=ExchangeId.BINANCE,
                    symbol_id="QTUMBTC",
                    min_notional=0.0001,
                    is_margin_trading_allowed=False,
                    price_precision=8,
                    qty_precision=1,
                ),
            ],
        },
        {
            "symbol": SymbolTable(
                id="QTUMETH",
                active=True,
                blacklist_reason="",
                quote_asset="",
                base_asset="",
                cooldown=0,
                cooldown_start_ts=0,
                description="",
                created_at=1763521181483,
                updated_at=1763521172856,
            ),
            "exchange_values": [
                SymbolExchangeTable(
                    exchange_id=ExchangeId.BINANCE,
                    symbol_id="QTUMETH",
                    min_notional=0.001,
                    is_margin_trading_allowed=False,
                    price_precision=7,
                    qty_precision=1,
                ),
            ],
        },
        {
            "symbol": SymbolTable(
                id="NEOBTC",
                active=True,
                blacklist_reason="",
                quote_asset="",
                base_asset="",
                cooldown=0,
                cooldown_start_ts=0,
                description="",
                created_at=1763521181422,
                updated_at=1763521172856,
            ),
            "exchange_values": [
                SymbolExchangeTable(
                    exchange_id=ExchangeId.BINANCE,
                    symbol_id="NEOBTC",
                    min_notional=0.0001,
                    is_margin_trading_allowed=False,
                    price_precision=8,
                    qty_precision=2,
                ),
                SymbolExchangeTable(
                    exchange_id=ExchangeId.KUCOIN,
                    symbol_id="NEOBTC",
                    min_notional=0.001,
                    is_margin_trading_allowed=False,
                    price_precision=6,
                    qty_precision=5,
                ),
            ],
        },
        {
            "symbol": SymbolTable(
                id="ETHBTC",
                active=True,
                blacklist_reason="",
                quote_asset="",
                base_asset="",
                cooldown=0,
                cooldown_start_ts=0,
                description="",
                created_at=1763521181258,
                updated_at=1763521172856,
            ),
            "exchange_values": [
                SymbolExchangeTable(
                    exchange_id=ExchangeId.BINANCE,
                    symbol_id="ETHBTC",
                    min_notional=0.0001,
                    is_margin_trading_allowed=False,
                    price_precision=5,
                    qty_precision=4,
                ),
                SymbolExchangeTable(
                    exchange_id=ExchangeId.KUCOIN,
                    symbol_id="ETHBTC",
                    min_notional=0.0001,
                    is_margin_trading_allowed=True,
                    price_precision=4,
                    qty_precision=6,
                ),
            ],
        },
    ]


def get_test_asset_indices():
    """Returns test asset index data"""
    return []


def get_test_symbol_index_links():
    """Returns symbol-to-index associations"""
    return []
