GET http://localhost:5000/bot/ HTTP/1.1

###

GET http://localhost:5000/bot/5f830e226b57f6eba97d93f6 HTTP/1.1

###

POST http://localhost:5000/bot/ HTTP/1.1
content-Type: application/json

{
    "pair": "BNBBUSD",
    "active": "false",
    "strategy": "short",
    "name": "Test short take profit",
    "so_size": "0",
    "take_profit": "0.003",
    "price_deviation_so": "0"
}

###
PUT http://localhost:5000/bot/5f830e226b57f6eba97d93f6 HTTP/1.1
content-Type: application/json

{
    "pair": "BNBBUSD",
    "name": "Test take profit",
    "strategy": "short"
}

###
DELETE http://localhost:5000/bot/5f830c917cb67ea5d0bd5972 HTTP/1.1

###

GET http://localhost:5000/bot/activate/6046b0e75b97144638063cf3 HTTP/1.1
