TOP_GAINER_EARLY_MOMENTUM_ALGO = "top_gainer_early_momentum"
TOP_LOSER_EARLY_MOMENTUM_ALGO = "top_loser_early_momentum"
TOP_MOVER_EARLY_MOMENTUM_ALGOS = frozenset(
    {
        TOP_GAINER_EARLY_MOMENTUM_ALGO,
        TOP_LOSER_EARLY_MOMENTUM_ALGO,
    }
)
TOP_GAINER_EARLY_MOMENTUM_PENDING_ENTRY_CANDLES = 1
TOP_GAINER_BREADTH_ALGO = "top_gainer_breadth"

TOP_GAINER_FAILURE_REVERSAL_ALGO = "top_gainer_failure_reversal"
TOP_GAINER_FAILURE_REVERSAL_PENDING_ENTRY_TTL_MS = 2 * 60 * 1000

RELATIVE_STRENGTH_IMPULSE_RIDER_ALGO = "relative_strength_impulse_rider"
RELATIVE_STRENGTH_IMPULSE_RIDER_PENDING_ENTRY_CANDLES = 1
