TOP_GAINER_EARLY_MOMENTUM_ALGO = "top_gainer_early_momentum"
TOP_LOSER_EARLY_MOMENTUM_ALGO = "top_loser_early_momentum"
TOP_MOVER_EARLY_MOMENTUM_ALGOS = frozenset(
    {
        TOP_GAINER_EARLY_MOMENTUM_ALGO,
        TOP_LOSER_EARLY_MOMENTUM_ALGO,
    }
)
TOP_GAINER_EARLY_MOMENTUM_PENDING_ENTRY_CANDLES = 1

RELATIVE_STRENGTH_IMPULSE_RIDER_ALGO = "relative_strength_impulse_rider"
RELATIVE_STRENGTH_IMPULSE_RIDER_PENDING_ENTRY_CANDLES = 1
