GET http://localhost:5000/account HTTP/1.1

###
GET http://localhost:5000/account/symbols HTTP/1.1

###
GET http://localhost:5000/account/update-assets HTTP/1.1

###
GET http://localhost:5000/account/assets HTTP/1.1
