POST http://localhost:5000/order/buy HTTP/1.1

{
    "pair": "BTCUSDT",
    "qty": "0.001442",
    "price": "7145"
}

###
POST http://localhost:5000/order/sell HTTP/1.1

{
    "pair": "BTCUSDT",
    "qty": "0.001442",
    "price": "7132.09"
}

### 

GET http://localhost:5000/order/order-updates HTTP/1.1