POST http://localhost:5000/order/buy HTTP/1.1

{
    "pair": "BNBBTC",
    "qty": "0.1",
    "price": "0.0020889"
}

###
POST http://localhost:5000/order/sell HTTP/1.1

{
    "pair": "BNBBTC",
    "qty": "0.1",
    "price": "0.0020887"
}


###
DELETE http://localhost:5000/order/BTCBNB/1234 HTTP/1.1


###
GET http://localhost:5000/order/poll HTTP/1.1

###
GET http://localhost:5000/order/all?limit=50&offset=10 HTTP/1.1



###
GET http://localhost:5000/order/open HTTP/1.1

