POST http://localhost:5000/order/buy HTTP/1.1

{
    "pair": "BTCUSDT",
    "qty": "0.001442",
    "price": "7520.64"
}

###
POST http://localhost:5000/order/sell HTTP/1.1

{
    "pair": "BTCUSDT",
    "qty": "0.001442",
    "price": "7513.18"
}
