import { BotStatus } from "../../utils/enums";

export interface Deal {
  current_price?: number;
  buy_price?: number;
  buy_timestamp?: number;
  sell_timestamp?: number;
  original_buy_price?: number;
  sell_price?: number;
  buy_total_qty?: number;
  trailling_stop_loss_price?: number;
  trailling_profit_price?: number;
  take_profit_price?: number;
  margin_short_buy_back_price?: number;
  margin_short_sell_price?: number;
  buy_back_price?: number;
  stop_loss_price?: number;
}

export interface Bot {
  id: string;
  name: string;
  status: string;
  balance_available: string;
  balance_available_asset: string;
  balance_size_to_use: number;
  base_order_size: number;
  // Deprecated in favor of fiat
  balance_to_use?: string;
  fiat?: string;
  buy_total_qty?: number;
  deal?: Deal;
  errors?: string[];
  logs?: string[];
  mode: string;
  pair: string;
  take_profit: number;
  trailling: boolean;
  trailling_deviation: number;
  dynamic_trailling: boolean;
  orders?: any[]; // Generated by Binance
  stop_loss: number;
  margin_short_reversal: boolean;
  safety_orders: any[];
  cooldown: number;
  strategy: string;
  short_buy_price: number;
  short_sell_price: number;
  commissions: number;
}

export interface BotEntity {
  ids: string[];
  entities: { [id: string]: Bot };
}

/**
 * This file contains redux state
 * that is shared between bots views
 * at the time of writing: bots and paper trading (test bots)
 */

// The initial state of the App
export const singleBot: Bot = {
  id: "",
  status: BotStatus.INACTIVE,
  balance_available: "0",
  balance_available_asset: "",
  balance_size_to_use: 0, // Centralized
  base_order_size: 50,
  balance_to_use: "USDC",
  errors: [],
  mode: "manual",
  name: `manual_${new Date().getTime().toString()}`,
  pair: "",
  take_profit: 2.3,
  trailling: false,
  trailling_deviation: 2.8,
  dynamic_trailling: false,
  deal: {},
  orders: [],
  stop_loss: 3,
  margin_short_reversal: true,
  safety_orders: [],
  cooldown: 0,
  strategy: "long",
  short_buy_price: 0,
  short_sell_price: 0,
  commissions: 0,
};
