import { BotStatus, BotStrategy } from "../../utils/enums";

export interface Deal {
  current_price?: number;
  buy_price?: number;
  buy_timestamp?: number;
  sell_timestamp?: number;
  original_buy_price?: number;
  sell_price?: number;
  buy_total_qty?: number;
  trailling_stop_loss_price?: number;
  trailling_profit_price?: number;
  take_profit_price?: number;
  margin_short_buy_back_price?: number;
  margin_short_sell_price?: number;
  buy_back_price?: number;
  stop_loss_price?: number;
}

export interface Bot {
  id: string;
  pair: string;
  fiat?: string;
  base_order_size: number;
  candle_interval?: string;
  close_condition?: string;
  cooldown: number;
  dynamic_trailling: boolean;
  logs: string[];
  mode: string;
  name: string;
  status: BotStatus;
  stop_loss: number;
  margin_short_reversal: boolean;
  take_profit: number;
  trailling: boolean;
  trailling_deviation: number;
  trailling_profit?: number;
  strategy: BotStrategy;
  total_commissions?: number;
  // Deprecated in favor of parity total_commissions
  commissions?: number;
  balance_available: number;
  balance_available_asset: string;
  deal?: Deal;
  orders?: any[]; // Generated by Exchange
}

export interface BotEntity {
  ids: string[];
  entities: { [id: string]: Bot };
}

/**
 * This file contains redux state
 * that is shared between bots views
 * at the time of writing: bots and paper trading (test bots)
 */

// The initial state of the App
export const singleBot: Bot = {
  id: "",
  status: BotStatus.INACTIVE,
  balance_available: 0,
  balance_available_asset: "",
  base_order_size: 50,
  fiat: "USDC",
  logs: [],
  mode: "manual",
  name: `terminal_${new Date().getTime().toString()}`,
  pair: "",
  take_profit: 2.3,
  trailling: false,
  trailling_deviation: 2.8,
  dynamic_trailling: false,
  deal: {
    current_price: 0,
    buy_price: 0,
    buy_timestamp: 0,
    sell_timestamp: 0,
    original_buy_price: 0,
    sell_price: 0,
    buy_total_qty: 0,
    trailling_stop_loss_price: 0,
    trailling_profit_price: 0,
    take_profit_price: 0,
    margin_short_buy_back_price: 0,
    margin_short_sell_price: 0,
    buy_back_price: 0,
    stop_loss_price: 0,
  },
  orders: [],
  stop_loss: 3,
  margin_short_reversal: true,
  cooldown: 0,
  strategy: BotStrategy.LONG,
  total_commissions: 0,
};
