GET http://localhost:5000/account HTTP/1.1

###
GET http://localhost:5000/account/symbols HTTP/1.1

### Symbols no cannibalism
GET http://localhost:5000/account/symbols/no-cannibal HTTP/1.1

###
GET http://localhost:5000/account/balance/raw HTTP/1.1

### With or without symbol
GET http://localhost:5000/account/ticker/BTCGBP HTTP/1.1

###
GET http://localhost:5000/account/ticker24/BTCUSDT HTTP/1.1

### Get PNL
GET http://localhost:5000/account/pnl?days=7 HTTP/1.1



### get estimated assets amount
GET http://localhost:5000/account/balance/estimate HTTP/1.1

### Find quote asset
GET http://localhost:5000/account/find-quote/BNBBTC HTTP/1.1

### Convert 0.0003 BTC to GBP
GET http://localhost:5000/account/conversion?base=BTC&quote=GBP&qty=0.0003 HTTP/1.1

### Raw symbols no cannibalism
GET http://localhost:5000/account/symbols/no-cannibal HTTP/1.1


## Test authenticaiton
GET http://localhost:5000/auth HTTP/1.1
