GET http://localhost:5000/account HTTP/1.1

###
GET http://localhost:5000/account/balance HTTP/1.1

###
GET http://localhost:5000/account/symbols HTTP/1.1

###
GET http://localhost:5000/account/assets HTTP/1.1

### With or without symbol
GET http://localhost:5000/account/ticker/BTCUSDT HTTP/1.1

###
GET http://localhost:5000/account/ticker24/BTCUSDT HTTP/1.1


### Assets endpoint
GET http://localhost:5000/account/update-assets HTTP/1.1


### Get PNL
GET http://localhost:5000/account/pnl?days=7 HTTP/1.1


### Find quote asset
GET http://localhost:5000/account/find-quote/BNBBTC HTTP/1.1