name: Deploy to Staging (home server)
on:
  workflow_run:
    workflows: ["Deployment checks"]
    types: [completed]
  workflow_dispatch:

env:
  ACTIONS_RUNNER_DEBUG: false

jobs:
  full-stack-deploy:
    if: >-
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
          tags: tag:ci

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "${{ secrets.STAGING_DEPLOY }}" > ~/.ssh/home_server_key
          chmod 600 ~/.ssh/home_server_key

          ssh-keyscan -p 2222 100.64.83.67 >> ~/.ssh/known_hosts

      - name: Deploy stack
        run: |
          ssh -i ~/.ssh/home_server_key \
            -p 2222 \
            "carkod@100.64.83.67" \
            'cd /var/www/terminal.binbot.in && docker compose up --pull always -d && docker image prune -f'
